//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagTMDBLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaggageEntities : DbContext
    {
        public BaggageEntities()
            : base("name=BaggageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OSUSR_UUK_BAGINTEG> OSUSR_UUK_BAGINTEG { get; set; }
        public virtual DbSet<OSUSR_UUK_BAGMSGS> OSUSR_UUK_BAGMSGS { get; set; }
        public virtual DbSet<OSUSR_UUK_BAGTIMESREFERENCE> OSUSR_UUK_BAGTIMESREFERENCE { get; set; }
        public virtual DbSet<OSUSR_UUK_EQUIPTYPE> OSUSR_UUK_EQUIPTYPE { get; set; }
        public virtual DbSet<OSUSR_UUK_FLT_INFO> OSUSR_UUK_FLT_INFO { get; set; }
        public virtual DbSet<OSUSR_UUK_H2H> OSUSR_UUK_H2H { get; set; }
        public virtual DbSet<OSUSR_UUK_RULES> OSUSR_UUK_RULES { get; set; }
        public virtual DbSet<OSUSR_UUK_TAXITIMES> OSUSR_UUK_TAXITIMES { get; set; }
        public virtual DbSet<OSUSR_UUK_PAXMSGS> OSUSR_UUK_PAXMSGS { get; set; }
        public virtual DbSet<OSUSR_UUK_PTM_H2H> OSUSR_UUK_PTM_H2H { get; set; }
        public virtual DbSet<OSUSR_UUK_PTM_REF_SEC_TIME> OSUSR_UUK_PTM_REF_SEC_TIME { get; set; }
        public virtual DbSet<OSUSR_UUK_PTMREFS2G> OSUSR_UUK_PTMREFS2G { get; set; }
        public virtual DbSet<OSUSR_UUK_REGISTRATIONS> OSUSR_UUK_REGISTRATIONS { get; set; }
    }
}

