//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagTMDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSUSR_UUK_FLT_INFO
    {
        public int ID { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<int> FLT_NR { get; set; }
        public string AC_REGISTRATION { get; set; }
        public string FROM_IATA { get; set; }
        public string TO_IATA { get; set; }
        public string DIV_IATA { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public Nullable<System.DateTime> ATD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<System.DateTime> ATA { get; set; }
        public Nullable<System.DateTime> ONBLOCK { get; set; }
        public string FROM_TERMINAL { get; set; }
        public string FROM_GATE { get; set; }
        public string FROM_STAND { get; set; }
        public string TO_TERMINAL { get; set; }
        public string TO_STAND { get; set; }
        public string TO_BELT { get; set; }
        public Nullable<System.DateTime> DOOROPEN { get; set; }
        public Nullable<System.DateTime> DOORCLOSED { get; set; }
        public Nullable<int> ASSIGNUSER { get; set; }
        public Nullable<bool> ISOTPDISMISS { get; set; }
        public string CF { get; set; }
        public string DBAGM { get; set; }
        public string DTT { get; set; }
        public string DH2H { get; set; }
        public string ALT { get; set; }
        public string ABAGM { get; set; }
    }
}
