//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagTMDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSUSR_UUK_RULES
    {
        public int ID { get; set; }
        public Nullable<int> LTYELLOW { get; set; }
        public Nullable<int> LTRED { get; set; }
        public Nullable<int> ARRIVBAGMAVG { get; set; }
        public Nullable<int> OTPYELLOW { get; set; }
        public Nullable<int> MCT { get; set; }
        public Nullable<int> CFYELLOW { get; set; }
        public Nullable<int> CFRED { get; set; }
        public Nullable<int> DEPBAGMLIMITE { get; set; }
        public Nullable<int> DEPBAGMRED { get; set; }
        public Nullable<int> PTYELLOW { get; set; }
        public Nullable<int> PTRED { get; set; }
        public Nullable<int> H2HYELLOW { get; set; }
        public Nullable<int> H2HRED { get; set; }
        public Nullable<int> DOORCLOSEALERT { get; set; }
    }
}
