//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagTMDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSUSR_UUK_BAGTIMESREFERENCE
    {
        public int ID { get; set; }
        public Nullable<int> EQUIPTYPEID { get; set; }
        public Nullable<int> BAG { get; set; }
        public Nullable<decimal> UNLTIME { get; set; }
        public Nullable<decimal> INJTIME { get; set; }
        public Nullable<decimal> DOLLIE_L { get; set; }
        public Nullable<decimal> HULL_L { get; set; }
    }
}
