//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagTMDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSUSR_UUK_PTMREFS2G
    {
        public int ID { get; set; }
        public string STAND { get; set; }
        public string SEC { get; set; }
        public string GATE { get; set; }
        public Nullable<int> MINUTES { get; set; }
    }
}
