//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagTMDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSUSR_BMT_BAGINTEG
    {
        public int ID { get; set; }
        public string NUMBER { get; set; }
        public string IFLIGHT { get; set; }
        public Nullable<System.DateTime> IDATE { get; set; }
        public string IORIGIN { get; set; }
        public string BPMIN { get; set; }
        public string BSMBOARDI { get; set; }
        public Nullable<System.DateTime> ATD { get; set; }
        public string OUTSEAT { get; set; }
        public string ISEAT { get; set; }
        public string FSEAT { get; set; }
        public string BPM_HUB { get; set; }
        public string BSMBOARD { get; set; }
        public string FFLTNR { get; set; }
        public Nullable<System.DateTime> FDATE { get; set; }
        public string FDEST { get; set; }
        public Nullable<System.DateTime> FLTATD { get; set; }
        public string CLOSE { get; set; }
        public string IAUT { get; set; }
        public string FAUT { get; set; }
        public Nullable<System.DateTime> IATD { get; set; }
        public Nullable<bool> ISRUSH { get; set; }
    }
}
