//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagTMDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSUSR_BMT_FLT_INFO
    {
        public int ID { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<int> FLT_NR { get; set; }
        public string FROM_IATA { get; set; }
        public string TO_IATA { get; set; }
        public string FROM_ICAO { get; set; }
        public string TO_ICAO { get; set; }
        public string DIV_IATA { get; set; }
        public string DIV_ICAO { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> BTD { get; set; }
        public Nullable<System.DateTime> ATD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> BTA { get; set; }
        public Nullable<System.DateTime> ATA { get; set; }
        public string FROM_TERMINAL { get; set; }
        public string FROM_GATE { get; set; }
        public string FROM_STAND { get; set; }
        public string AC_REGISTRATION { get; set; }
        public string TO_TERMINAL { get; set; }
        public string TO_GATE { get; set; }
        public string TO_STAND { get; set; }
        public Nullable<System.DateTime> ONBLOCK { get; set; }
        public string TO_BELT { get; set; }
        public Nullable<int> ISASSIGN { get; set; }
        public Nullable<int> ASSIGNUSER { get; set; }
        public Nullable<bool> ISOTPDISMISS { get; set; }
    }
}
