//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagTMDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSUSR_UUK_H2H
    {
        public int ID { get; set; }
        public string IFLTNR { get; set; }
        public Nullable<System.DateTime> IDATE { get; set; }
        public Nullable<int> IFLTINFOID { get; set; }
        public string IORIGIN { get; set; }
        public string ISTAND { get; set; }
        public Nullable<System.DateTime> IETA { get; set; }
        public Nullable<System.DateTime> IATA { get; set; }
        public Nullable<System.DateTime> HULLOPEN { get; set; }
        public Nullable<decimal> IUNLOAD { get; set; }
        public Nullable<decimal> ITAXI { get; set; }
        public Nullable<decimal> IINJECT { get; set; }
        public Nullable<System.DateTime> ETU { get; set; }
        public Nullable<int> INRBAGS { get; set; }
        public string ONTOFLIGHT { get; set; }
        public Nullable<int> HUB { get; set; }
        public string OFLTNR { get; set; }
        public Nullable<System.DateTime> ODATE { get; set; }
        public Nullable<int> OFLTINFOID { get; set; }
        public Nullable<int> OLNRBAGS { get; set; }
        public Nullable<decimal> OINJECT { get; set; }
        public Nullable<decimal> OTAXI { get; set; }
        public Nullable<decimal> OLOAD { get; set; }
        public Nullable<System.DateTime> ETL { get; set; }
        public Nullable<System.DateTime> ETLU { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public Nullable<System.DateTime> HULLCLOSE { get; set; }
        public Nullable<System.DateTime> ATD { get; set; }
        public string STANDD { get; set; }
        public string CR { get; set; }
    }
}
