//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagTMDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSUSR_BMT_BSM
    {
        public int ID { get; set; }
        public string SMI { get; set; }
        public string SLMI { get; set; }
        public string STATUSINDICATOR { get; set; }
        public string BIRREG { get; set; }
        public string CCORP { get; set; }
        public string DREMOTELOC { get; set; }
        public string EEXCEP { get; set; }
        public string FFLTNR { get; set; }
        public Nullable<System.DateTime> FDATE { get; set; }
        public string FDEST { get; set; }
        public string FCLASS { get; set; }
        public string HHANDTERM { get; set; }
        public string HHANDBAY { get; set; }
        public string HHANDSTDGTE { get; set; }
        public string IFLTNR { get; set; }
        public Nullable<System.DateTime> IDATE { get; set; }
        public string IORIGINAPT { get; set; }
        public string ICLASS { get; set; }
        public string JRECO { get; set; }
        public string JAGENTID { get; set; }
        public string JSCANID { get; set; }
        public string JREADLOC { get; set; }
        public string JSENTLOC { get; set; }
        public string KDMP { get; set; }
        public string LPNR { get; set; }
        public string NBAGTAG { get; set; }
        public string NNRTAGS { get; set; }
        public string OFTTNR { get; set; }
        public Nullable<System.DateTime> ODATE { get; set; }
        public string ODESTAPT { get; set; }
        public string OCLASS { get; set; }
        public string PPAXNAME { get; set; }
        public string RINTERNAL { get; set; }
        public string SAUTL { get; set; }
        public string SSEAT { get; set; }
        public string SPAXCK { get; set; }
        public string SPAXPROF { get; set; }
        public string SAUTTRANS { get; set; }
        public string SBAGTAGSTATUS { get; set; }
        public string TTAGPRINTERID { get; set; }
        public string UULD { get; set; }
        public string UCOMPT { get; set; }
        public string UTYPEOFBAG { get; set; }
        public string UDESTCONTAINER { get; set; }
        public string UCONTTYPE { get; set; }
        public string VBAGSOURCIND { get; set; }
        public string VCITY { get; set; }
        public string WPWINDICATOR { get; set; }
        public string WNRCKBAGS { get; set; }
        public Nullable<int> WTOTK { get; set; }
        public string XSECURITY { get; set; }
        public string YFQTV { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
    }
}
