//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagTMDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSUSR_UUK_TAXITIMES
    {
        public int ID { get; set; }
        public string FROM { get; set; }
        public Nullable<int> STANDTYPEID { get; set; }
        public string TO { get; set; }
        public Nullable<int> TAXITIME { get; set; }
    }
}
