//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagTMDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSUSR_UUK_PTM_H2H
    {
        public int ID { get; set; }
        public string IFLTNR { get; set; }
        public Nullable<System.DateTime> IDATE { get; set; }
        public Nullable<int> IFLTINFOID { get; set; }
        public string IORIGIN { get; set; }
        public string STAND { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<int> SEC { get; set; }
        public Nullable<int> HUB { get; set; }
        public Nullable<System.DateTime> ETCG { get; set; }
        public Nullable<System.DateTime> ETG { get; set; }
        public Nullable<System.DateTime> ETGU { get; set; }
        public string OFLTNR { get; set; }
        public Nullable<System.DateTime> ODATE { get; set; }
        public Nullable<int> OFLTINFOID { get; set; }
        public string ODEST { get; set; }
        public string GATE { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public Nullable<int> ECONOMY { get; set; }
        public Nullable<int> BUSINESS { get; set; }
        public Nullable<int> FIRST { get; set; }
        public string STATUS { get; set; }
        public string DEP { get; set; }
    }
}
