//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagTMDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSUSR_UUK_PAXMSGS
    {
        public int ID { get; set; }
        public string IFLTNR { get; set; }
        public Nullable<System.DateTime> IDATE { get; set; }
        public string IORIGIN { get; set; }
        public string OFLTNR { get; set; }
        public Nullable<System.DateTime> ODATE { get; set; }
        public string ODEST { get; set; }
        public Nullable<int> FIRST { get; set; }
        public Nullable<int> BUSINESS { get; set; }
        public Nullable<int> ECONOMY { get; set; }
        public Nullable<int> INF { get; set; }
        public Nullable<int> CHD { get; set; }
        public string RESERVATIONSTATUS { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
    }
}
