//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagTMDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSUSR_UUK_PTM_REF_SEC_TIME
    {
        public int ID { get; set; }
        public string WEEK { get; set; }
        public Nullable<System.DateTime> FROM_TIME { get; set; }
        public Nullable<System.DateTime> TO_TIME { get; set; }
        public Nullable<int> TIME { get; set; }
    }
}
